<?php

namespace App\Support;

/**
 * Builds the FLW-protocol compliance summary and supplies the PDF translation
 * strings. Shared by the authenticated report endpoint (ReportController) and
 * the public demo (DemoController) so the demo report is numerically identical
 * to the real one. Stateless.
 */
class WasteReportBuilder
{
    public const FLW_MAPPING = [
        'protein'  => ['group' => 'Meat & Seafood / Pulses', 'eu_code' => '02 02 / 20 01 08'],
        'veg'      => ['group' => 'Vegetables & Fruits', 'eu_code' => '02 01 / 20 01 08'],
        'dairy'    => ['group' => 'Dairy & Eggs', 'eu_code' => '02 05 / 20 01 08'],
        'prepared' => ['group' => 'Prepared & Processed Foods', 'eu_code' => '20 01 08'],
    ];

    /**
     * @param  \Illuminate\Support\Collection  $rows  category/reason aggregate rows
     *                                                 (total_kg, entry_count)
     */
    public function buildSummary($rows): array
    {
        $summary = [];

        foreach (array_keys(self::FLW_MAPPING) as $category) {
            $categoryRows = $rows->where('category', $category);
            $flw = self::FLW_MAPPING[$category];

            $byReason = [];
            foreach ($categoryRows as $row) {
                $byReason[$row->reason] = [
                    'total_kg' => round((float) $row->total_kg, 2),
                    'entry_count' => $row->entry_count,
                ];
            }

            $summary[$category] = [
                'category' => $category,
                'flw_group' => $flw['group'],
                'eu_code' => $flw['eu_code'],
                'total_kg' => round($categoryRows->sum('total_kg'), 2),
                'entry_count' => $categoryRows->sum('entry_count'),
                'by_reason' => $byReason,
            ];
        }

        return $summary;
    }

    /**
     * PDF label translations. Falls back to English for unsupported locales.
     */
    public function translations(string $locale): array
    {
        $tr = [
            'en' => [
                'title'             => 'EU Food Waste Compliance Report',
                'reporting_period'  => 'Reporting Period',
                'establishment'     => 'Establishment',
                'generated_by'      => 'Generated By',
                'generated_on'      => 'Generated On',
                'regulatory_label'  => 'Regulatory Reference',
                'total_waste'       => 'Total Food Waste',
                'entries'           => 'entries',
                'summary_title'     => 'Summary by FLW Category',
                'col_category'      => 'Category',
                'col_flw_group'     => 'FLW Group',
                'col_eu_code'       => 'EU Waste Code',
                'col_total_kg'      => 'Total (kg)',
                'col_entries'       => 'Entries',
                'col_pct'           => '% of Total',
                'total'             => 'TOTAL',
                'breakdown_title'   => 'Breakdown by Waste Reason',
                'col_reason'        => 'Reason',
                'col_row_total'     => 'Row Total (kg)',
                'reasons'           => ['spoilage' => 'Spoilage', 'overproduction' => 'Overproduction', 'expiry' => 'Expiry', 'prep_waste' => 'Prep Waste', 'other' => 'Other'],
                'categories'        => ['protein' => 'Protein', 'veg' => 'Vegetables', 'dairy' => 'Dairy', 'prepared' => 'Prepared'],
                'individual_title'  => 'Individual Entries',
                'showing_entries'   => 'Showing all :count entries for the selected period.',
                'col_date'          => 'Date',
                'col_item'          => 'Item',
                'col_weight'        => 'Weight (kg)',
                'col_source'        => 'Source',
                'source_scan'       => 'Scan',
                'source_manual'     => 'Manual',
                'attestation_title' => 'Attestation',
                'attestation_text'  => 'I confirm that this report accurately reflects the food waste generated by :name during the period :from to :to, and that this data has been collected in accordance with the FLW Protocol measurement methodology required under EU Directive 2018/851.',
                'sig_signature'     => 'Signature',
                'sig_date'          => 'Date',
                'sig_title'         => 'Title / Role',
            ],
            'nl' => [
                'title'             => 'EU Nalevingsrapport Voedselverspilling',
                'reporting_period'  => 'Rapportageperiode',
                'establishment'     => 'Instelling',
                'generated_by'      => 'Gegenereerd door',
                'generated_on'      => 'Gegenereerd op',
                'regulatory_label'  => 'Regelgevingsreferentie',
                'total_waste'       => 'Totale voedselverspilling',
                'entries'           => 'invoeren',
                'summary_title'     => 'Overzicht per FLW-categorie',
                'col_category'      => 'Categorie',
                'col_flw_group'     => 'FLW-groep',
                'col_eu_code'       => 'EU-afvalcode',
                'col_total_kg'      => 'Totaal (kg)',
                'col_entries'       => 'Invoeren',
                'col_pct'           => '% van totaal',
                'total'             => 'TOTAAL',
                'breakdown_title'   => 'Uitsplitsing per afvalreden',
                'col_reason'        => 'Reden',
                'col_row_total'     => 'Rijtotaal (kg)',
                'reasons'           => ['spoilage' => 'Bederf', 'overproduction' => 'Overproductie', 'expiry' => 'Verlopen THT', 'prep_waste' => 'Bereidingsafval', 'other' => 'Overig'],
                'categories'        => ['protein' => 'Proteïne', 'veg' => 'Groenten', 'dairy' => 'Zuivel', 'prepared' => 'Bereid gerecht'],
                'individual_title'  => 'Individuele invoeren',
                'showing_entries'   => 'Alle :count invoeren voor de geselecteerde periode.',
                'col_date'          => 'Datum',
                'col_item'          => 'Product',
                'col_weight'        => 'Gewicht (kg)',
                'col_source'        => 'Bron',
                'source_scan'       => 'Scan',
                'source_manual'     => 'Handmatig',
                'attestation_title' => 'Attestatie',
                'attestation_text'  => 'Ik bevestig dat dit rapport de voedselverspilling van :name nauwkeurig weergeeft voor de periode :from tot :to, en dat deze gegevens zijn verzameld conform de FLW Protocol-meetmethodologie vereist onder EU-richtlijn 2018/851.',
                'sig_signature'     => 'Handtekening',
                'sig_date'          => 'Datum',
                'sig_title'         => 'Functie / Rol',
            ],
            'de' => [
                'title'             => 'EU-Konformitätsbericht Lebensmittelabfall',
                'reporting_period'  => 'Berichtszeitraum',
                'establishment'     => 'Betrieb',
                'generated_by'      => 'Erstellt von',
                'generated_on'      => 'Erstellt am',
                'regulatory_label'  => 'Rechtsgrundlage',
                'total_waste'       => 'Gesamter Lebensmittelabfall',
                'entries'           => 'Einträge',
                'summary_title'     => 'Übersicht nach FLW-Kategorie',
                'col_category'      => 'Kategorie',
                'col_flw_group'     => 'FLW-Gruppe',
                'col_eu_code'       => 'EU-Abfallcode',
                'col_total_kg'      => 'Gesamt (kg)',
                'col_entries'       => 'Einträge',
                'col_pct'           => '% des Gesamten',
                'total'             => 'GESAMT',
                'breakdown_title'   => 'Aufschlüsselung nach Abfallgrund',
                'col_reason'        => 'Grund',
                'col_row_total'     => 'Zeilensumme (kg)',
                'reasons'           => ['spoilage' => 'Verderb', 'overproduction' => 'Überproduktion', 'expiry' => 'Ablauf MHD', 'prep_waste' => 'Zubereitungsabfall', 'other' => 'Sonstiges'],
                'categories'        => ['protein' => 'Protein', 'veg' => 'Gemüse', 'dairy' => 'Milchprodukte', 'prepared' => 'Zubereitete Speisen'],
                'individual_title'  => 'Einzeleinträge',
                'showing_entries'   => 'Alle :count Einträge für den gewählten Zeitraum.',
                'col_date'          => 'Datum',
                'col_item'          => 'Bezeichnung',
                'col_weight'        => 'Gewicht (kg)',
                'col_source'        => 'Quelle',
                'source_scan'       => 'Scan',
                'source_manual'     => 'Manuell',
                'attestation_title' => 'Bestätigung',
                'attestation_text'  => 'Ich bestätige, dass dieser Bericht den Lebensmittelabfall von :name für den Zeitraum :from bis :to korrekt widerspiegelt und dass diese Daten gemäß der FLW-Protokoll-Messmethodik erhoben wurden, wie in der EU-Richtlinie 2018/851 gefordert.',
                'sig_signature'     => 'Unterschrift',
                'sig_date'          => 'Datum',
                'sig_title'         => 'Titel / Funktion',
            ],
            'fr' => [
                'title'             => 'Rapport de conformité UE — Déchets alimentaires',
                'reporting_period'  => 'Période de rapport',
                'establishment'     => 'Établissement',
                'generated_by'      => 'Généré par',
                'generated_on'      => 'Généré le',
                'regulatory_label'  => 'Référence réglementaire',
                'total_waste'       => 'Total des déchets alimentaires',
                'entries'           => 'entrées',
                'summary_title'     => 'Résumé par catégorie FLW',
                'col_category'      => 'Catégorie',
                'col_flw_group'     => 'Groupe FLW',
                'col_eu_code'       => 'Code déchet UE',
                'col_total_kg'      => 'Total (kg)',
                'col_entries'       => 'Entrées',
                'col_pct'           => '% du total',
                'total'             => 'TOTAL',
                'breakdown_title'   => 'Répartition par raison de gaspillage',
                'col_reason'        => 'Raison',
                'col_row_total'     => 'Total ligne (kg)',
                'reasons'           => ['spoilage' => 'Détérioration', 'overproduction' => 'Surproduction', 'expiry' => 'Date de péremption', 'prep_waste' => 'Déchets de préparation', 'other' => 'Autre'],
                'categories'        => ['protein' => 'Protéines', 'veg' => 'Légumes', 'dairy' => 'Produits laitiers', 'prepared' => 'Plats préparés'],
                'individual_title'  => 'Entrées individuelles',
                'showing_entries'   => 'Affichage des :count entrées pour la période sélectionnée.',
                'col_date'          => 'Date',
                'col_item'          => 'Aliment',
                'col_weight'        => 'Poids (kg)',
                'col_source'        => 'Source',
                'source_scan'       => 'Scan',
                'source_manual'     => 'Manuel',
                'attestation_title' => 'Attestation',
                'attestation_text'  => 'Je confirme que ce rapport reflète fidèlement les déchets alimentaires générés par :name durant la période du :from au :to, et que ces données ont été collectées conformément à la méthodologie de mesure du protocole FLW requise par la directive UE 2018/851.',
                'sig_signature'     => 'Signature',
                'sig_date'          => 'Date',
                'sig_title'         => 'Titre / Rôle',
            ],
            'es' => [
                'title'             => 'Informe de cumplimiento UE — Desperdicio alimentario',
                'reporting_period'  => 'Período de informe',
                'establishment'     => 'Establecimiento',
                'generated_by'      => 'Generado por',
                'generated_on'      => 'Generado el',
                'regulatory_label'  => 'Referencia normativa',
                'total_waste'       => 'Total de desperdicio alimentario',
                'entries'           => 'entradas',
                'summary_title'     => 'Resumen por categoría FLW',
                'col_category'      => 'Categoría',
                'col_flw_group'     => 'Grupo FLW',
                'col_eu_code'       => 'Código residuo UE',
                'col_total_kg'      => 'Total (kg)',
                'col_entries'       => 'Entradas',
                'col_pct'           => '% del total',
                'total'             => 'TOTAL',
                'breakdown_title'   => 'Desglose por motivo de desperdicio',
                'col_reason'        => 'Motivo',
                'col_row_total'     => 'Total fila (kg)',
                'reasons'           => ['spoilage' => 'Deterioro', 'overproduction' => 'Sobreproducción', 'expiry' => 'Caducidad', 'prep_waste' => 'Residuo de preparación', 'other' => 'Otro'],
                'categories'        => ['protein' => 'Proteína', 'veg' => 'Verduras', 'dairy' => 'Lácteos', 'prepared' => 'Preparados'],
                'individual_title'  => 'Entradas individuales',
                'showing_entries'   => 'Mostrando las :count entradas del período seleccionado.',
                'col_date'          => 'Fecha',
                'col_item'          => 'Alimento',
                'col_weight'        => 'Peso (kg)',
                'col_source'        => 'Fuente',
                'source_scan'       => 'Escáner',
                'source_manual'     => 'Manual',
                'attestation_title' => 'Atestación',
                'attestation_text'  => 'Confirmo que este informe refleja con exactitud el desperdicio alimentario generado por :name durante el período del :from al :to, y que estos datos se han recopilado conforme a la metodología de medición del protocolo FLW requerida por la Directiva UE 2018/851.',
                'sig_signature'     => 'Firma',
                'sig_date'          => 'Fecha',
                'sig_title'         => 'Cargo / Función',
            ],
        ];

        return $tr[$locale] ?? $tr['en'];
    }
}
